#!/usr/bin/env bash
#
# Script name: dmsearch
# Description: Search various search engines (inspired by surfraw).
# Dependencies: dmenu and a web browser
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# Contributors: Derek Taylor

# Defining our web browser.
DMBROWSER="brave-browser-stable"

# An array of search engines.  You can edit this list to add/remove
# search engines. The format must be: "engine_name - url".
# The url format must allow for the search keywords at the end of the url.
# For example: https://www.amazon.com/s?k=XXXX searches Amazon for 'XXXX'.
declare -a options=(
" youtube - https://www.youtube.com/watch?v=5qap5aO4i9A"
" udemy - https://voidlinux.org/packages/"
" googleimages - https://www.google.com/search?hl=en&tbm=isch&q="
" linuxtips - https://voidlinux.org/packages/"
" github - https://github.com/AyslanBatista/Void-Linux"
" github - https://www.youtube.com/watch?v=5qap5aO4i9A"
" gitlab - https://gitlab.com/search?search="
" voidlinux - https://voidlinux.org/packages/"
" translate - https://translate.google.com/?sl=auto&tl=en&text="
"quit"
)

# Picking a search engine.
while [ -z "$engine" ]; do
enginelist=$(printf '%s\n' "${options[@]}" | rofi -dmenu -i 20 -p 'Escolha seu buscador:') || exit
engineurl=$(echo "$enginelist" | awk '{print $NF}')
engine=$(echo "$enginelist" | awk '{print $1}')
done

# Searching the chosen engine.
while [ -z "$query" ]; do
query=$(rofi -dmenu -i 20 -p "Searching $engine:") || exit
done

# Display search results in web browser
$DMBROWSER "$engineurl""$query"

