# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '




#PATH=$PATH:$HOME/Scripts


# xrandr
alias xrandr2560='xrandr --output HDMI-0 --mode 2560x1080'
alias xrandr1920='xrandr --output Virtual1 --mode 1920x1080'
alias xrandr1280='xrandr --output HDMI-0 --mode 1280x720'

# Aplicativos
alias vim='nvim'


# Void
alias xr='sudo xbps-remove'
alias xl='sudo xbps-install'
alias xu='sudo xbps-install -Su'

# Files
alias rc.lua='vim .config/awesome/rc.lua'
alias yml='vim .config/alacritty/alacritty.yml'
alias bashrc='vim .bashrc'
alias gtk='vim .config/gtk-3.0/gtk.css'
alias roteiros='vim Documentos/TWMLINUX'
alias zshrc='vim .zshrc'
alias picom.conf='vim .config/picom/picom.conf'
alias keybinds='vim .config/awesome/Keybinds'
alias twm.vim='sudo nvim /usr/share/nvim/runtime/colors/twm.vim'
alias theme.blue='sudo nvim /usr/share/awesome/themes/blue/theme.lua'


